### ISSUE TITLE
Keep getting to no-op logger/loggerfactory

### ISSUE THREAD

**Issue by doronavin** [bright/slf4android#12]
Hi, what do I need to do in order to user and AndroidLoggerFactory and not the default AndroidLoggerFactory?

Thanks.

**Comment by miensol** [comment]
Hi :) I'm sorry but I probably don't get what you mean, can you describe your problem in more detail?

**Comment by doronavin** [comment]
Yes. 
First, thanks for the quick reply. 
I'm trying to use the logger by using the following lines:

 FileLogHandlerConfiguration fileHandler = LoggerConfiguration.fileLogHandler(application);
            fileHandler.setFullFilePathPattern("/sdcard/temp/temp.%g.%u.log");
            LoggerConfiguration.configuration().addHandlerToRootLogger(fileHandler);
            String logFileName = fileHandler.getCurrentFileName();
            Log.d("loggerBootstrapper", "file name: "+logFileName);


and adding this line to bulid.gradle:

compile('com.github.bright:slf4android:0.1.3'){
        transitive = true
    }


But when I use the following code:

    private static final Logger logger = LoggerFactory.getLogger(lProjectsPresenter.class.getSimpleName());

I'm getting the NOPLogger Logger and not an actual logger

This is the logger I'm getting:
org.slf4j.helpers.NOPLogger(NOP)

**Comment by miensol** [comment]
Are you sure the ` private static final Logger logger = LoggerFactory.getLogger(lProjectsPresenter.class.getSimpleName());` is called after the configuration part?

**Comment by doronavin** [comment]
Yes. The configuration happens during bootstrap and the retrieval happens later(I've also removed  the static modifier on the logger - happens every time an instance of the presenter is being instantiated.

When debugging, I see that it is using the StaticLoggerBinder - org.slf4j.impl.StaticLoggerBinder from two different jars (slf4android-0.1.3 (classes.jar) and self4j-nop-1.7.12.jar) and during execution, it is using the noOp version and not the slf4android version. I'm not using the no-op version in bulid.gradle. Maybe some other library uses it? Is there a way to force it to use the slf4android version instead? Thanks

**Comment by miensol** [comment]
Yes that's possible - but you should see (hopefully) a warning from slf4j. 
You can find that with i.e.  `gradle --offline -q dependencies app:dependencies | grep slf4j -B 4`

**Comment by doronavin** [comment]
Hi, 

It seems the following libarary is using it.
com.layer.sdk

For example: 

+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12


I have no idea where to go from here.

I tried excluding it from layer using to following line:

compile ('com.layer.sdk:layer-sdk:0.20.3'){
        exclude group: 'org.slf4j', module: 'slf4j-nop:1.7.12'
    }

But it is not working.

Do you have any idea what can I do to make the slf4j-android module work?

Thanks.


Down below is what I got from you command line.

+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12
--
+--- com.basgeekball:awesome-validation:1.1
|    \--- com.google.guava:guava:18.0
+--- com.layer.sdk:layer-sdk:0.20.3
|    +--- com.google.android.gms:play-services-gcm:8.4.0 (*)
|    \--- org.slf4j:slf4j-nop:1.7.12
|         \--- org.slf4j:slf4j-api:1.7.12
--
|         \--- com.android.support:support-annotations:23.2.1 -> 23.4.0
+--- com.mikhaellopez:circularimageview:3.0.2
+--- com.commit451:NativeStackBlur:1.0.2
\--- com.github.bright:slf4android:0.1.3
     \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.12

**Comment by miensol** [comment]
It's really hard to figure out with this formatting how the graph looks like.

I've looked at [layer docs](https://developer.layer.com/docs/android/integration#installation-and-setup) and it says that one should add following deps to a project:
```
dependencies {
    compile 'com.layer.sdk:layer-sdk:0.20.4'
    compile 'com.google.android.gms:play-services-gcm:7.5.0'
    compile 'org.slf4j:slf4j-nop:1.5.8'
}
```

Just to double check you **don't have the line with `compile 'org.slf4j:slf4j-nop:...'`**? If you do you can safely adjust it to i.e.:
```
dependencies {
    compile('com.layer.sdk:layer-sdk:0.20.4'){
       exclude group: 'org.slf4j'
    }
    compile 'com.google.android.gms:play-services-gcm:7.5.0'
}
```

**Comment by doronavin** [comment]
Thanks. 
I really appreciate your help.
I didn't explicitly added compile 'org.slf4j:slf4j-nop:1.5.8'
but when using your exclude line - that did the trick. 
Finally, I can see lines of text...

**Comment by miensol** [comment]
Glad I could help 👍
