### ISSUE TITLE
[Question] Logging to a file

### ISSUE THREAD

**Issue by bolatov** [bright/slf4android#7]
I am trying to add slf4android logger to my application and use logging to a file functionality. Unfortunately, nothing is written to a file. Thus, I have several questions:

1. Where would the logs be written if a device lacks an SD-card?
2. Logging to a file is activated by adding the `.addHandlerToLogger("", ...);` to the application class. Does empty string activate the logging to a file for all loggers in the app or each logger name should be added?

**Comment by miensol** [comment]
To start logging to a file take a look at updated [Readme](/bright/slf4android).
```
FileLogHandlerConfiguration fileHandler = LoggerConfiguration.fileLogHandler(this)
LoggerConfiguration.configuration().addHandlerToRootLogger(fileHandler);
String logFileName = fileHandler.getCurrentFileName();
// logFileName contains full path to logged file
```
As mentioned there the place where the log file is written by default is determined by Android (as in [java.util.logging.FileHandler](http://developer.android.com/reference/java/util/logging/FileHandler.html)). 
The file name (pattern) code looks like this:
```
new File(context.getApplicationInfo().dataDir, context.getPackageName() + ".%g.%u.log")
```
Meaning that the files will be stored in `context.getApplicationInfo().dataDir` which is `/data/data/your.package/`.

Note that you can change the location yourself by i.e.:
```
FileLogHandlerConfiguration fileHandler = LoggerConfiguration.fileLogHandler(this)
fileHandler.setFullFilePathPattern("/sdcard/your.package/my_log.%g.%u.log")
```
However you have to make sure that the app will have write permissions to that location.
