### ISSUE TITLE
Log level

### ISSUE THREAD

**Issue by iwanglian** [bright/slf4android#8]
I set Level in Application
      FileLogHandlerConfiguration fileHandler = LoggerConfiguration.fileLogHandler(this);
        fileHandler.setLevel(Level.INFO);
       
but the TRACE log would printed in Log file.

**Comment by miensol** [comment]
Please try latest version `0.1.2`

**Comment by iwanglian** [comment]
I have use 0.1.0 ,and set like this
       LoggerConfiguration.configuration().setRootLogLevel(LogLevel.WARNING);

It works

**Comment by miensol** [comment]
Yes, this will work too in a slightly different manner though. `LoggerConfiguration.configuration().setRootLogLevel(LogLevel.WARNING)` sets log level on all loggers and thus affects all handlers (including logcat, file, crashlytics etc).
